export const INCREMENT_ITEM = "INCREMENT_ITEM";
export const DECREMENT_ITEM = "DECREMENT_ITEM";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
export const ADD_ITEM_TO_WISHLIST = "ADD_ITEM_TO_WISHLIST";
export const MOVE_ITEM_FROM_CART_TO_WISHLIST =
  "MOVE_ITEM_FROM_CART_TO_WISHLIST";
export const MOVE_ITEM_FROM_WISHLIST_TO_CART =
  "MOVE_ITEM_FROM_WISHLIST_TO_CART";
export const ADD_ALL_WISHLIST_ITEMS_TO_CART = "ADD_ALL_WISHLIST_ITEMS_TO_CART";
